name: SSH into EC2 and Run Commands

on:
  push:
    branches:
      - database-query

jobs:
  ssh_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy File to EC2
        run: |
          sudo scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no moodle07102023.sql ubuntu@${{ secrets.EC2_INSTANCE_IP }}:/test
        # env:
        #   EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}

      - name: SSH into EC2 and Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ubuntu # Replace with your EC2 instance's username
          key: ${{ secrets.SSH_PEM_KEY }}
          script: |
            # Replace the following commands with your desired commands
            echo "Connected to EC2 instance"
            # sudo pg_restore -h ${{ secrets.AWS_RDS_HOST }} -U ${{ secrets.AWS_RDS_USER }} -d ${{ secrets.AWS_RDS_DATABASE }} -v /test/moodle07102023.sql
            pg_restore --clean -U  ${{ secrets.AWS_RDS_USER }} -d ${{ secrets.AWS_RDS_DATABASE }} -v /test/moodle07102023.sql
        env:
          PGPASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
